### PR TITLE
Structure installer using classes

### PR DESCRIPTION
**Pull request by martin-bts**

### CODE REVIEW

**Comment by evgenyfadeev** [comment]
Martin, I've looked at the 'askbot-setup' script about a week ago and noticed the following issues:

- name of the app is hardcoded "askbot_app" - it should be changeable (maybe it should follow the same pattern as django start_project command - i.e by default create a structure like <dir_name>/<dir_name> and have the manage.py in the outer directory and the settings.py etc in the inner. and if the user chooses so - <dir_name>/<proj_name>
- manage.py file was not taking into account name of the project directory
- it should warn if any of <dir_name>/<proj_name>/*.py or <dir_name>/manage.py, etc. would be overwritten. The old implementation works but assumes that all files are in the project root directory.

I've made some changes on branch askbot-deployment-11  - perhaps you could have a look and see if any of that might be useful.

**Comment by evgenyfadeev** [comment]
@martin-bts really like the structure you've created:).

**Comment by martin-bts** [comment]
DO NOT MERGE THIS! THIS IS FOR REVIEW ONLY!

**Comment by martin-bts** [comment]
Superceeded by https://github.com/ASKBOT/askbot-devel/pull/849

**Pull request closed without merging**
