### PR TITLE
Add basic, mostly empty pre-commit and ruff

### PR DESCRIPTION
**Pull request by boxydog**
Also run it in the github tests.

### CODE REVIEW

**Comment by boxydog** [comment]
After merging this, the next step would be to start uncommenting the ruff rules and letting it fix them, or fixing them manually if need be. pyupgrade and django-upgrade also very helpful.

This will change hundreds of lines of code in shallow ways to be closer to python 3 best practices. For example, using `foo.a` instead of `getattr(foo, "a")`.

**Comment by boxydog** [comment]
Again, personally I would squash-commit all PRs, but it's your project.

**Comment by boxydog** [comment]
FYI, this passed: https://github.com/boxydog/askbot-devel/actions. Not sure why it doesn't show up on the PR. Different repo, I guess.

**Comment by evgenyfadeev** [comment]
@boxydog I'll be reviewing these Fri-Mon, but possibly earlier. Thank you!

**Comment by boxydog** [comment]
Note with this new pyproject.toml, it works to replace the deprecated `python setup.py install` with `python -m pip install .`. See also https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#setup-py-deprecated.

Also, you can use [`pip-compile`](https://pypi.org/project/pip-tools/) to create a real `requirements.txt` with all requirements pinned.

**Pull request merged**
