### PR TITLE
Use `apps.ready` instead of `loading.app_cache_ready`

### PR DESCRIPTION
**Pull request by ratson**
As `loading.app_cache_ready` is deprecated.

### CODE REVIEW

**Comment by evgenyfadeev** [comment]
Hey, thanks for the PR's - could you have a look at the test cases and make the python manage.py test askbot.tests run in one go? I think the issue is with the page_page_load tests.

**Comment by ratson** [comment]
@evgenyfadeev I find that tests `askbot/tests/test_thread_model.py` and `askbot/tests/test_permission_assertions.py` are failing regardless this PR.

The error is
```
PermissionDenied: Sorry, you cannot join or leave groups because your account is blocked.</br> Your account might be blocked in error - please contact the site administrators, if you think so.
```

**Comment by evgenyfadeev** [comment]
@ratson I know, these tests have nothing to do with this PR. The tests actually pass when they are run separately. The issue is that there is some state carry-over from one test to another, just asked for you to have a look if you want. Otherwise - never mind.

**Comment by martin-bts** [comment]
The problem with the tests arises from SQLite. It has been reported in https://github.com/ASKBOT/askbot-devel/issues/711 and I am circumventing it by using Postgresql. I only started reading through PRs. I have a similar patch included in https://github.com/ASKBOT/askbot-devel/pull/792

**Pull request merged**
