### PR TITLE
Added ordering without Haystack

### PR DESCRIPTION
**Pull request by ZuluPro**
Without it, I can't order my questions.
Maybe I'm doing wrong, just give 2-3 tips if it's the case.

### CODE REVIEW

**Comment by evgenyfadeev** [comment]
Maybe there is some mistake? For me sorting works in postgres.
It won't work with Haystack enabled.

**Comment by ZuluPro** [comment]
@evgenyfadeev But I don't see where the sorting is made ?

With SQLite and MySQL, my threads are always ordered by date, whatever the value of `orderby`.

**Comment by ZuluPro** [comment]
Hello @evgenyfadeev 
I tested sorting here : https://github.com/ZuluPro/askbot-devel/commit/baa4717a23e63f281edb9def6d45990c541af204

With no success:
```
======================================================================
FAIL: test_run_advanced_search_sort (askbot.tests.thread_model_tests.RunAdvancedSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zulu/projects/askbot-devel/askbot/tests/thread_model_tests.py", line 144, in test_run_advanced_search_sort
    self.assertNotEqual(threads[0].id, sorted_threads[0].id)
AssertionError: 1 == 1
```

**Comment by evgenyfadeev** [comment]
Ok, got it, this issue is specific to master branch. I think you've changed the boolean logic when doing the PEP changes. Fixed in commit 04b3743b76d93163e30d2a2ddf66dfff12014ef6

**Pull request closed without merging**
