### PR TITLE
require coffin < 2.0.0

### PR DESCRIPTION
**Pull request by stapelberg**
https://pypi.python.org/pypi/Coffin/2.0.0 was released a day ago (2015-04-17) and breaks askbot installation, the error message is https://gist.github.com/stapelberg/989a8324b0af7dac9894

See also https://github.com/coffin/coffin/issues/88

### CODE REVIEW

**Comment by evgenyfadeev** [comment]
Why exactly <0.2.0 ? For me version 0.3.8 works.

**Comment by stapelberg** [comment]
Sorry, that was a typo in the title. The version restriction is actually < 2.0.0, because that new version breaks. I’ve update the pull request, please take another look.

**Comment by evgenyfadeev** [comment]
Yeah, got it, thanks.

**Comment by evgenyfadeev** [comment]
Test cases fail with 0.4.0, so will limit to 0.3.8

**Comment by evgenyfadeev** [comment]
done in https://github.com/ASKBOT/askbot-devel/commit/61807f1987b05bb4c6fb7beac1ad2bccb6b3353a

0.4.0 did not work for me, the latest working version is 0.3.8

**Pull request closed without merging**
