### PR TITLE
[WIP] Added settings to configure allowed elements & attrs in HTML sanitization

### PR DESCRIPTION
**Pull request by ZuluPro**
I created my custom `Markdown`, but wasn't able to add attribute "id" to tags, neither add iframe tags (useful for videos).

I also PEP8-ized `askbot/utils/html.py` and added tests to my feature

### CODE REVIEW

**Comment by evgenyfadeev** [comment]
I think it would be better to allow customizing entire markdown converter than adding more extra ad-hoc settings. Perhaps if you create a better converter it could replace the current one. 

Also there is a js preview converter, would be cool to auto-generate the js version based on Python or vs versa to be sure that the preview matches the server side rendering.

**Comment by ZuluPro** [comment]
@evgenyfadeev OK,

If I understand your note, I replace [`askbot.utils.markup.markdown_input_converter`](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/utils/markup.py#L208) by a `markdown2.Markdown` class which does all the job ?

**Comment by evgenyfadeev** [comment]
Replace it by your own function to which path can be specified via setting ASKBOT_MARKDOWN_CONVERTER, the function would take input text and return html.

**Comment by ZuluPro** [comment]
In fact my problem is the following:
[`sanitize_html`](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/utils/html.py#L53) doesn't allow me to put the attribute I want: `'id'`, `'data-image'` & `'data-description'.`
I use it to format images with JS.

And `sanitize_html` is really used a lot, so change ``ASKBOT_MARKDOWN_CONVERTER`` won't help me...

**Comment by evgenyfadeev** [comment]
I will refactor this file a bit then you'll be able to do what you want. Data attributes allow to implement XSS in some cases, so I've disallowed them, but you will be able to relax that on your setup.

**Comment by evgenyfadeev** [comment]
I've changed settings that can be used to remove elements and attributes as well and made settings.py names:
ASKBOT_ALLOWED_HTML_ELEMENTS and ASKBOT_ALLOWED_HTML_ATTRIBUTES

**Pull request merged**
